# Setup
title:               Not a blog
tagline:             'Making the world a better place, one commit at a time'
description:         'My non-blog.'
url:                 https://jzohrab.github.io
baseurl:             /
paginate:            5
permalink:           pretty

excerpt_separator: <!--end_excerpt-->

remote_theme: poole/lanyon

# About/contact
author:
  name:              Jeff Zohrab
  email:             jzohrab@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             0.0.1
google_analytics_id: #UA-XXXX-Y
